### ISSUE TITLE
请教一下，代码变更后的覆盖率汇总有考虑过相关的方案吗？

### ISSUE THREAD

**Issue by starry-ww** [erduoniba/hdcoverage#10]
app 在某个版本的测试中，会有多次的打包（代码变更）操作。每个包测试时，都会进行代码覆盖率相关文件的收集。
在版本末期，想要对历史的代码覆盖率文件进行合并操作，统计这个版本最终的app增量覆盖率。

请问下是否有考虑实现相关的场景，或有相关的思路可以分享下吗？

**Comment by erduoniba** [comment]
覆盖率合并不太好实现，因为每次打包的代码都不一样，暂时还没有办法说以那个commit的代码为对照线进行输出。
