### ISSUE TITLE
pod install 后，好像报了个错误如下图

### ISSUE THREAD

**Issue by khchcker** [erduoniba/hdcoverage#14]
![image](https://user-images.githubusercontent.com/16751397/195531221-7e9288d5-9320-4d74-a899-153b7d7dbe87.png)

**Comment by khchcker** [comment]
![image](https://user-images.githubusercontent.com/16751397/195530889-abeeb474-3ea9-49f0-88e4-795a7ff6ab56.png)

**Comment by erduoniba** [comment]
可以检查一下你本地的 ruby 版本：
```
$ ruby -v
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin20]
```

然后看看 https://blog.csdn.net/ckw1988/article/details/51535114 这个能否解决问题

**Comment by khchcker** [comment]
> 可以检查一下你本地的 ruby 版本：
> 
> ```
> $ ruby -v
> ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin20]
> ```
> 
> 然后看看 https://blog.csdn.net/ckw1988/article/details/51535114 这个能否解决问题

升级到了2.7.1， 还是一样 
#<Xcodeproj::Project> path:`/Volumes/Data/workspace/xcode/hdcoverage/Example/HDCoverage.xcodeproj` UUID:`607FACC81AFB9204008FA782`
[!] An error occurred while processing the post-install hook of the Podfile.

No such file or directory @ dir_initialize - /Volumes/Data/workspace/xcode/hdcoverage/Example/Classes

/Volumes/Data/workspace/xcode/hdcoverage/Example/Podfile:84:in `open'
/Volumes/Data/workspace/xcode/hdcoverage/Example/Podfile:84:in `foreach'
/Volumes/Data/workspace/xcode/hdcoverage/Example/Podfile:84:in `addFilesToGroup'
/Volumes/Data/workspace/xcode/hdcoverage/Example/Podfile:104:in `block (3 levels) in from_ruby'
/Volumes/Data/workspace/xcode/hdcoverage/Example/Podfile:41:in `each'
/Volumes/Data/workspace/xcode/hdcoverage/Example/Podfile:41:in `block (2 levels) in from_ruby'
/Users/user/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/podfile.rb:179:in `post_install!'

**Comment by erduoniba** [comment]
**问题：** 可否提供一个支持swift高一点的版本， 当前有遇到xcode14, swift5.5.2好像不能用 pod install 后，好像报了个错误如下图

**解决方案：**
可以在这个路径下打开 HDCoverageSFramework.xcodeproj 工程，然后使用你本地的Xcode14编译得到最新的 `HDCoverageSFramework.framework`，然后替换主工程的即可：
<img width="734" alt="image" src="https://user-images.githubusercontent.com/6082855/195755547-975a0356-2382-4e54-8bf0-35d0ac40988c.png">

**Comment by erduoniba** [comment]
> > 可以检查一下你本地的 ruby 版本：
> > ```
> > $ ruby -v
> > ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin20]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然后看看 https://blog.csdn.net/ckw1988/article/details/51535114 这个能否解决问题
> 
> 升级到了2.7.1， 还是一样 #Xcodeproj::Project path:`/Volumes/Data/workspace/xcode/hdcoverage/Example/HDCoverage.xcodeproj` UUID:`607FACC81AFB9204008FA782` [!] An error occurred while processing the post-install hook of the Podfile.
> 
> No such file or directory @ dir_initialize - /Volumes/Data/workspace/xcode/hdcoverage/Example/Classes
> 
> /Volumes/Data/workspace/xcode/hdcoverage/Example/Podfile:84:in `open' /Volumes/Data/workspace/xcode/hdcoverage/Example/Podfile:84:in `foreach' /Volumes/Data/workspace/xcode/hdcoverage/Example/Podfile:84:in `addFilesToGroup' /Volumes/Data/workspace/xcode/hdcoverage/Example/Podfile:104:in `block (3 levels) in from_ruby' /Volumes/Data/workspace/xcode/hdcoverage/Example/Podfile:41:in `each' /Volumes/Data/workspace/xcode/hdcoverage/Example/Podfile:41:in `block (2 levels) in from_ruby' /Users/user/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/podfile.rb:179:in `post_install!'

这个是我这边在 `1.1.3` 版本添加了一些iOS代码导致 `pod install` 失败。 `1.1.4` 版本已经修复该问题，感谢提出缺陷。

**Comment by khchcker** [comment]
现在build也成功了，已经安装到模拟器上了，  就是出现了另外一个问题， 模拟器上启动， 报了个错误， 这个一般是什么原因呢
![image](https://user-images.githubusercontent.com/16751397/195771313-026cdf3e-8462-4272-90b7-f0800d368fbe.png)

**Comment by khchcker** [comment]
模拟器上再次打开，出现这个崩溃
![image](https://user-images.githubusercontent.com/16751397/195771956-8bf5f59c-0a97-421b-af77-4cd55a9f0084.png)

**Comment by erduoniba** [comment]
更新一下最新的代码试试看

**Comment by khchcker** [comment]
> 

 最新的代码， 好像又有上面的pod install 错误

**Comment by erduoniba** [comment]
> > 
> 
> 最新的代码， 好像又有上面的pod install 错误

最后一次提交是这个，我本地测试ok的
提交：
f17012eb1c0e4c317a0e0750d690a38b32325dbb [f17012e]
父级：
[565b226ed1](rev://565b226ed1a0415019fba18b82907052b02c8b83)
日期：
2022年10月14日 GMT+8 14:04:10
标签：
HEAD master origin/master origin/HEAD

**Comment by khchcker** [comment]
之前我xcode是13的时候，曾经成功过次， 如下右边图，现在我自己打的HDCoverageSFramework包好像有问题，
1、在MachOFiles 在外层没有HDCoverage.o， 可能与静态包有关，可以给一份最新的HDCoverageSFramework源码么
![image](https://user-images.githubusercontent.com/16751397/195837368-659c926c-3553-49d6-af6b-534e59519f39.png)


2、GenerateMergeOFiles，一些静态库的好像没有 左边的是全的，右边的不全
![image](https://user-images.githubusercontent.com/16751397/195837090-7d9958ae-61a0-47e3-af5c-92fdb6999d3a.png)

**Comment by erduoniba** [comment]
1、HDCoverageSFramework源码也在这个仓库中（下载本工程之后可以找到的）：
https://github.com/erduoniba/hdcoverage/tree/master/HDCoverageSFramework
Xcode14没有生成合并的目标文件（.o）需要看看执行脚本后的提示了，可能是有符合冲突，我升级试试看。
2、静态库需要源码，或者在生存静态库的时候插桩得到目标文件（.o）

**Comment by erduoniba** [comment]
最新的代码使用Xode14beta3编译通过了，@khchcker 你那边可能需要再检查下了。

**Comment by khchcker** [comment]
> 
生成报告在这一步的时候，失败了， 请问下，这个需要更新那个东西， 
+ xcrun llvm-cov export /Users/user/hdcoverage/Example/CoverageResult/MachOFiles/HDCoverage.o -instr-profile=/Users/user/hdcoverage/Example/CoverageResult/Profraw/HDCoverage.profdata -format=lcov

**error: /Users/user/hdcoverage/Example/CoverageResult/MachOFiles/HDCoverage.o: Failed to load coverage: Unsupported coverage format version**

**Comment by erduoniba** [comment]
> > 
> 
> 生成报告在这一步的时候，失败了， 请问下，这个需要更新那个东西，
> 
> * xcrun llvm-cov export /Users/user/hdcoverage/Example/CoverageResult/MachOFiles/HDCoverage.o -instr-profile=/Users/user/hdcoverage/Example/CoverageResult/Profraw/HDCoverage.profdata -format=lcov
> 
> **error: /Users/user/hdcoverage/Example/CoverageResult/MachOFiles/HDCoverage.o: Failed to load coverage: Unsupported coverage format version**

试试把 MachOFiles 文件目录删掉看看

**Comment by khchcker** [comment]
> 试试把 MachOFiles 文件目录删掉看看

这个是删除后的，不会报错，但是也没有报告生成，MachOFiles里的插桩文件应该是报告生成的基础吧

![image](https://user-images.githubusercontent.com/16751397/196889751-7f13be5a-eb99-4d0b-97f9-feb0cdce5f3a.png)
