### ISSUE TITLE
ld：报错 duplicate symbol. ___llvm_profile_runtime in

### ISSUE THREAD

**Issue by khchcker** [erduoniba/hdcoverage#15]
![image](https://user-images.githubusercontent.com/16751397/200504609-8a86735b-9801-40d2-8046-4909b3758a9d.png)

**Comment by erduoniba** [comment]
看着是符号重复了导致，因为我这个组件本身就带有了报错的符号，你的工程中就不需要再次声明。

**Comment by erduoniba** [comment]
移除你工程中，编译报错的函数就好。
