### ISSUE TITLE
config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'设置后，我们的工程代码崩溃了

### ISSUE THREAD

**Issue by ZhengXiuQun** [erduoniba/hdcoverage#17]
你好，我想咨询下，为什么release要设置SWIFT_OPTIMIZATION_LEVEL为-Onone，为发现不设置，有些函数没有被计算入覆盖率的统计。但是我们项目，release 设置SWIFT_OPTIMIZATION_LEVEL为-Onone，会发现崩溃，您这边能否帮忙解释下为什么需要设置SWIFT_OPTIMIZATION_LEVEL为-Onone

**Comment by erduoniba** [comment]
原理请参考：https://github.com/erduoniba/hdcoverage/issues/18

另外崩溃信息可以提供一下吗？
