### ISSUE TITLE
ld: scattered reloc r_address too large for architecture armv7

### ISSUE THREAD

**Issue by lyon888** [erduoniba/hdcoverage#19]
# 将多个目标文件手动链接然后生成组合目标文件
ld -r -o $machoFiles/$PROJECT.o $generateMergeOFiles/*.o
--------------------------------------------------------
你好，在上述生成组合目标文件时报了
ld: scattered reloc r_address too large for architecture armv7
这个错误，请问该怎么处理呢

**Comment by erduoniba** [comment]
这个问题，我并没有经验去解决它，不过我通过 chatgpt4 咨询了下，解决方案也转发给你看一下，希望对你有帮助：

这个错误信息表示在编译时，链接器（ld）遇到了一个问题：对于armv7架构，分散的重定位（scattered reloc）的r_address值过大。这可能是由于项目中的某些库或者代码不兼容armv7架构导致的。
为了解决这个问题，您可以尝试以下方法：
检查项目中使用的第三方库是否支持armv7架构。如果不支持，您可以尝试更新这些库或者寻找替代方案。
如果您的应用不需要支持armv7架构，您可以在项目设置中移除对armv7的支持。在Xcode中，选择项目的target，然后在"Build Settings"中找到"Architectures"设置。将"Architectures"中的armv7移除，仅保留arm64。
如果问题仍然存在，您可以尝试清理项目缓存（Product > Clean Build Folder），然后重新编译项目。
