### ISSUE TITLE
能把AFNetwoking或者自定一个组件加入到Demo么？😭

### ISSUE THREAD

**Issue by yexiayun** [erduoniba/hdcoverage#2]
我这里测试生成的报告不包含pod里的文件

**Comment by yexiayun** [comment]
调试了很久，demo 里 ，use_frameworks! 去掉就好了，动态库会有自己的二进制文件。

**Comment by erduoniba** [comment]
动态库其实是需要自己在动态库进行代码覆盖率收集的。其实demo中也有说明。

**Comment by erduoniba** [comment]
1.1.1版本脚本已经支持动态库。demo也使用AFNworking作为动态库实践了。
