### ISSUE TITLE
打包ipa后收集不到覆盖率

### ISSUE THREAD

**Issue by dizhouyunnu** [erduoniba/hdcoverage#21]
作者您好，拜读了您的大作，我这边打算基于profraw来收集iphone app上手工测试的覆盖率，目前xcode下真机debug可以正常收集，但是打包成ipa测试包，testflight下载安装以后不能再收集到profraw。
想问下您，通过ipa方式安装后，有可能收集到profraw文件吗，需要什么特殊的配置；或是什么原理会导致这条路走不通，感谢您。
我感觉是有可能走通的，因为真机调试时，拔掉usb线，仍能正常收到profraw。

我的被测工程是objectc语言

**Comment by erduoniba** [comment]
我这边的项目中通过企业包（Release包）测试是ok的，需要你在 Xcode 中多检查一下 Build Settings 的差异了。比如说 OTHER_CFLAGS、OTHER_SWIFT_FLAGS、OTHER_LDFLAGS，都需要检查一下。
文章中的 `3、工程配置代码覆盖率参数：` 部分有详细的配置信息。可以认真看一下。
