### ISSUE TITLE
genhtml: command not found

### ISSUE THREAD

**Issue by syyjay** [erduoniba/hdcoverage#22]
hd_parse_profraw_gather.sh: line 72: genhtml: command not found

**Comment by erduoniba** [comment]
`genhtml` 是一个用于生成代码覆盖率报告的工具。它通常与代码覆盖率工具（如gcov）一起使用，用于将收集到的代码覆盖率数据转换为可视化的HTML报告。`genhtml` 会解析收集到的覆盖率数据，并根据源代码文件的覆盖情况生成相应的报告，以便开发人员更好地了解代码的测试覆盖率情况。这些报告通常包括覆盖率百分比、覆盖率细节和源代码高亮显示等信息，有助于开发人员评估测试的完整性和质量。

1、你可以打开终端，输入：
```
➜  ~ which genhtml    
/usr/local/bin/genhtml
```
来检查是否有 `genhtml` 

2、在 macOS 上安装 genhtml 可以通过以下步骤进行操作：
2.1、确保您已经安装了 Xcode 命令行工具。打开终端并运行以下命令来检查是否已安装：
```
xcode-select --version
```
如果未安装，终端会提示您安装 Xcode 命令行工具。按照提示进行安装。

2.2、安装 gcov 工具集。gcov 通常是 GCC 编译器的一部分。您可以使用 Homebrew 包管理器来安装 GCC 和 gcov。在终端中运行以下命令来安装 Homebrew（如果尚未安装）：
```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

2.3、安装完成后，运行以下命令来安装 GCC 和 gcov：
```
brew install gcc
```
安装完 gcov 工具集后，genhtml 工具应该已经包含在其中。您可以在终端中运行以下命令来验证 genhtml 是否已经安装成功：
```
genhtml --version
```
如果 genhtml 安装成功，终端会显示 genhtml 的版本信息。
