### ISSUE TITLE
前面几个问题已经解决。

### ISSUE THREAD

**Issue by yexiayun** [erduoniba/hdcoverage#4]
1、AFNetworking没有覆盖率的问题：
 把use_framework!去掉，静态库没有问题。或者在你自己的组件podsepc里加 s.static_framework = true。因为静态库的代码会被合并到app的主二进制文件里，llvm-cov 可以从这个二进制里读取覆盖率信息。

2、不支持动态库的问题：要用llvm-cov show -arch=arm64 你的动态库二进制文件 动态库里生成的profdata文件 
因为动态库的二进制文件是独立的，不在app的主二进制文件里，所以要单独读取。

Demo里hd_parse_profraw.sh 是：
xcrun llvm-cov show $2 -instr-profile=$profraws/$1.profdata -use-color -format=html -output-dir $result/$1
改成
xcrun llvm-cov show -arch=arm64 $2 -instr-profile=$profraws/$1.profdata -use-color -format=html -output-dir $result/$1

注意多了-arch=arm64 

建议还是读一下：https://llvm.org/docs/CommandGuide/llvm-cov.html

**Comment by erduoniba** [comment]
第2点你这么说也没有问题，你那边的错误信息应该是：
error: /Users/denglibing/HDProject/HarryProject/iOS/hdcoverage/Example/CoverageResult/MachOFiles/HDCoverageDemo: Failed to load coverage: Unknown architecture named: 
根据提示，是可以添加 `-arch=arm64/x86_64` 来解决。
那么这里其实会存在另外的问题，就是多个动态库如何解决的问题。

**Comment by erduoniba** [comment]
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/6082855/155933460-8c6d953c-fabf-42e4-97b9-d530bf2886dd.png">
1.1.1版本脚本已经支持动态库。demo也使用AFNworking作为动态库实践了。

**Comment by Akries** [comment]
llvm cov 的时候一直报Failed to load coverage: Malformed coverage data ，这是啥原因呢

**Comment by gt-xiangchao** [comment]
> llvm cov 的时候一直报Failed to load coverage: Malformed coverage data ，这是啥原因呢

这个问题解决了吗

**Comment by gt-xiangchao** [comment]
> llvm cov 的时候一直报Failed to load coverage: Malformed coverage data ，这是啥原因呢

这个问题解决了吗

**Comment by QiyuSama** [comment]
> llvm cov 的时候一直报Failed to load coverage: Malformed coverage data ，这是啥原因呢
你好，这个问题解决了吗？同样遇到了
