### ISSUE TITLE
Duplicate Symbol '___llvm_profile_runtime'

### ISSUE THREAD

**Issue by lzenjoy** [erduoniba/hdcoverage#5]
您好，作者：在参考你的范例在我们自己的项目（项目比较庞大）进行应用时，链接环节出现了如下的错误，是通过xcodebuild方式进行编译的

[x] duplicate symbol '___llvm_profile_runtime' in
[x] duplicate symbol '___llvm_profile_runtime' in
[x] ld: 80 duplicate symbols for architecture arm64
[x] clang: error: linker command failed with exit code 1 (use -v to see invocation)

![Header](https://user-images.githubusercontent.com/24887501/163909541-092fbc97-88ed-468f-8163-86d0bf9e1b62.png)
![Podfile](https://user-images.githubusercontent.com/24887501/163909553-af15be0e-31d5-4ba6-921a-62a95df3ee2f.png)

**Comment by erduoniba** [comment]
@lzenjoy 这个是 OTHER_LDFLAGS 没有配置 正确导致。上面的 139 行代码是在 Test的config才生效，请检查下跑不起来是不是没有使用这个 config导致。
