### ISSUE TITLE
LLVM编译报错

### ISSUE THREAD

**Issue by CodeOuyang** [erduoniba/hdcoverage#6]
大佬 InstrProfiling.h 不能放在单独的pod里引用吗，编译就报下面的错

Undefined symbols for architecture x86_64:
  "___llvm_profile_write_file", referenced from:
      +[CodeCoverageTool writeCoverageToFile] in CodeCoverageTool.o
  "___llvm_profile_set_filename", referenced from:
      +[CodeCoverageTool registerCoverage:projectPath:] in CodeCoverageTool.o
ld: symbol(s) not found for architecture x86_64

**Comment by erduoniba** [comment]
放在pod中也可以，但是需要使得这个pod是静态库
