### ISSUE TITLE
实际应用中，saveAndUpload中的覆盖率文件可能会很大，一般上传时机是什么样的？

### ISSUE THREAD

**Issue by yexiayun** [erduoniba/hdcoverage#9]

**Comment by erduoniba** [comment]
看你们的推广场景了，这里有两个建议：
1、如果测试场景数据真实比较多，可以在某个页面让内部开发测试自己点击上传（插桩的包是无法提交审核的），展示进度；
2、如果数据少，直接在App进入后台上传就好。很快的。
